services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: medirag_qdrant
    restart: always
    ports:
      - "6333:6333" # Puerto para la API REST
      - "6334:6334" # Puerto para GRPC (más rápido para ingestión masiva)
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
